---
- name: Install k3s masters
  hosts: masters
  become: yes
  tasks:
    - name: Install k3s server on first masters
      ansible.builtin.shell: |
        curl -sfL https://get.k3s.io | sh -s - server --cluster-init --tls-san {{ master_hostname }}
      when: inventory_hostname == groups['masters'][0]
      run_once: true

    - name: Get k3s token from first masters
      ansible.builtin.shell: |
        cat /var/lib/rancher/k3s/server/node-token
      when: inventory_hostname == groups['masters'][0]
      register: k3s_token
      run_once: true

- name: Install k3s workers
  hosts: workers
  become: yes
  tasks:
    - name: Install k3s agent
      ansible.builtin.shell: |
        curl -sfL https://get.k3s.io | sh -s - agent \
          --server https://{{ master_hostname }}:6443 \
          --token {{ hostvars[groups['masters'][0]].k3s_token.stdout }}

- name: Retrieve kubeconfig from master
  hosts: masters[0]
  tasks:
    - name: Get kubeconfig
      become: yes
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ lookup('env','TF_ROOT') }}/kubeconfig"
        flat: yes

    - name: Update kubeconfig with correct server address
      ansible.builtin.replace:
        path: "{{ lookup('env','TF_ROOT') }}/kubeconfig"
        regexp: "server: https://127.0.0.1:6443"
        replace: "server: https://{{ master_hostname }}:6443"
      delegate_to: localhost
