- name: prepare VM
  hosts: all
  become: true
  vars:
    package_src: "files/rust-tools.deb" # Укажите локальный путь к пакету
    package_dest: "/tmp/rust-tools.deb"
  tasks:
    - name: install software
      apt:
        pkg:
          - mc
          - git
          - vim
          - htop
        state: latest
        update_cache: true
    - name: Copy .deb package to the remote server
      copy:
        src: "{{ package_src }}"
        dest: "{{ package_dest }}"
        mode: "0644"

    - name: Install the .deb package
      apt:
        deb: "{{ package_dest }}"
        state: present

- import_playbook: k3s.yml

- name: Final Play
  hosts: localhost
  tasks:
    - name: Display completion message
      debug:
        msg: "All playbooks completed"
