# Vagrantfile

require 'yaml'  # Подключаем библиотеку для работы с YAML

# Читаем файл конфигурации YAML
vm_configs = YAML.load_file("vm_configs.yml")

Vagrant.configure("2") do |config|
  # Цикл для создания виртуальных машин на основе данных из YAML файла
  vm_configs.each do |vm_config|
    config.vm.define vm_config["name"] do |vm|
      vm.vm.box = vm_config["box"]

      # Настройка имени хоста
      vm.vm.hostname = vm_config["hostname"]

      # Настройка сетевого интерфейса с IP-адресом
      vm.vm.network "private_network", ip: vm_config["ip"]

      # Настройки для VirtualBox
      vm.vm.provider "virtualbox" do |vb|
        vb.memory = vm_config["memory"]
        vb.cpus = vm_config["cpus"]

        vb.customize ["modifyvm", :id, "--cpuexecutioncap", "100"]
        vb.customize ["modifyvm", :id, "--memory", vm_config["memory"]]
        vb.customize ["modifyvm", :id, "--cpus", vm_config["cpus"]]
        vb.customize ["modifyvm", :id, "--name", vm_config["name"]]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

        vb.customize ["createhd", "--filename", "#{vm_config['name']}_disk.vdi", "--size", vm_config["disk_size"]]
        vb.customize ["storageattach", :id, "--storagectl", "SATA Controller", "--port", 0, "--device", 0, "--type", "hdd", "--medium", "#{vm_config['name']}_disk.vdi"]
      end

      # Настройки для VMware Desktop
      vm.vm.provider "vmware_desktop" do |v|
        v.vmx["memsize"] = vm_config["memory"].to_s
        v.vmx["numvcpus"] = vm_config["cpus"].to_s
        v.vmx["virtualHW.version"] = "16"
        v.verify_vmnet = false

        # Настройка диска для VMware
        v.vmx["scsi0:0.fileName"] = "#{vm_config['name']}_disk.vmdk"
        v.vmx["scsi0:0.present"] = "TRUE"
        v.vmx["scsi0:0.deviceType"] = "scsi-hardDisk"
        v.vmx["scsi0.virtualDev"] = "lsilogic"
      end

      # Настройка Ansible Provisioner
      vm.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
        ansible.inventory_path = "inventory.ini"
      end
    end
  end
end
