- name: ubuntu_24_04
  box: bento/ubuntu-24.04
  memory: 2048
  cpus: 1
  disk_size: 40960
  hostname: ubuntu24.local
  ip: 192.168.73.101

- name: ubuntu_22_04
  box: bento/ubuntu-22.04
  memory: 2048
  cpus: 1
  disk_size: 40960
  hostname: ubuntu22.local
  ip: 192.168.73.102