name: Terraform

on:
  push:
    branches: ["ci"]
  pull_request:
  workflow_dispatch: # позволяет запускать вручную при необходимости

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/yc
    permissions:
      contents: read
      id-token: write # для OIDC (если используете)

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: debug
        run: |
          env
          pwd
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8 # нужная версия

      - name: Restore Yandex Cloud key.json safely
        run: |
          mkdir -p ~/.yc
          echo "${{ secrets.YC_KEY_JSON }}" > ~/.yc/key.json
        shell: bash

      - name: Terraform Init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init -input=false

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        # if: github.event_name == 'pull_request'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: echo "${{ secrets.YC_KEY_JSON }}" > key.json && terraform plan -input=false -no-color -out=tfplan

      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform apply -auto-approve
  apply:
    name: Terraform Apply (Manual Approval)
    needs: plan
    runs-on: terraform/yc
    environment:
      name: production
      url: https://example.com
    defaults:
      run:
        working-directory: infra/terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Download plan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: infra/terraform

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve tfplan
